<?php include $phireHeader; ?>
    <h1 class="clicks-header"><?=$title; ?></h1>
<?php if (count($clicks) > 0): ?>
<?php if (null !== $pages): ?>
    <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
    <nav id="clicktrack-nav">
        <a class="normal-link" href="<?=$phireUri . '/clicks?filter=content';?>">Content</a> <span class="clicktrack-pad">|</span> <a class="normal-link" href="<?=$phireUri . '/clicks?filter=media';?>">Media</a> <span class="clicktrack-pad">|</span> <a class="normal-link" href="<?=$phireUri . '/clicks?filter=error';?>">Error</a> <span class="clicktrack-pad">|</span> <a class="normal-link" href="<?=$phireUri . '/clicks';?>">All</a>
    </nav>
    <form id="clicks-form" action="<?=$phireUri . '/clicks'; ?>" method="post">
        <table class="data-table" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <th><a href="<?=$phireUri . '/clicks?sort=id' . ((null !== $filter) ? '&filter=' . $filter : null); ?>">#</a></th>
                <th><a href="<?=$phireUri . '/clicks?sort=uri' . ((null !== $filter) ? '&filter=' . $filter : null); ?>">URI</a></th>
                <th><a href="<?=$phireUri . '/clicks?sort=type' . ((null !== $filter) ? '&filter=' . $filter : null); ?>">Type</a></th>
                <th><a href="<?=$phireUri . '/clicks?sort=clicks' . ((null !== $filter) ? '&filter=' . $filter : null); ?>">Clicks</a></th>
                <th>Uniques</th>
                <th class="text-center"><input type="checkbox" name="checkall" id="checkall" value="rm_clicks" /></th>
            </tr>
<?php $i = 1; ?>
<?php foreach ($clicks as $click): ?>
            <tr>
                <td><?=$click->id; ?></td>
                <td><?=$click->uri; ?></td>
                <td><span<?=(($click->type == 'error') ? ' style="color: #f00;"' : null); ?>><?=$click->type; ?></span></td>
                <td><?=$click->clicks; ?></a></td>
                <td><?=$click->uniques; ?></a></td>
                <td class="text-center"><input type="checkbox" name="rm_clicks[]" id="rm_clicks<?=$i++; ?>" value="<?=$click->id; ?>" /></td>
            </tr>
<?php endforeach; ?>
        </table>
        <div id="form-footer"><input style="float: right;" type="submit" name="submit" class="process-btn" value="Remove" /><span style="float: right; margin: 5px 15px 0 0;">Clear All? <input type="checkbox" name="clear_all" value="1" /></span></div>
    </form>
<?php else: ?>
    <p>There are currently no clicks in the click log.</p>
<?php endif; ?>
<?php include $phireFooter; ?>
